### PR TITLE
Architect updates

### PR DESCRIPTION
**Pull request by ibains**

### CODE REVIEW

**Comment by Pete-Dingwall** [comment]
Just made a quick edit as the formatting wasn't working for the headings (lack of leading space after the # format mark). I've also asked the ID Management team to review, will feedback and/or approve following that feedback.

**Review by ibains — COMMENTED** [review]
Hi Pete - are these the only changes that you would like? If so, please can you approve so we can merge. Thanks

**Review by luke-slowen — CHANGES_REQUESTED** [review]
I'm not sure the changes are syncing up correctly between different commits... feels like we've gone back a step with your latest @Pete-Dingwall - have a look at the commit before?

**Comment by luke-slowen** [comment]
This one @Pete-Dingwall https://github.com/DFE-Digital/architecture/pull/71/commits/c72938f67e8e02f7f5bf2411669bb8150a981c12

**Comment by Pete-Dingwall** [comment]
> This one @Pete-Dingwall [c72938f](https://github.com/DFE-Digital/architecture/commit/c72938f67e8e02f7f5bf2411669bb8150a981c12)

Yup, that's fine. Not sure what happened but that looks ok. The version I checked didn't have spaces after the # markup so was just showing # in the markdown rather than the headings. I just updated to add the spaces and make the headings show correctly/

**Review by luke-slowen — APPROVED** [review]

**Pull request merged**
